Colocando o hover no gantt
Madson-Carvalho/Allocation-Manager-Fe pull request #17
Opened 2024-11-30 02:26 UTC by RodrigoTDonde

2024-11-30 02:29 UTC, mateuskons approved these changes
Nice rodrigo

2024-12-01 17:05 UTC, Madson-Carvalho requested changes

2024-12-01 17:05 UTC, Madson-Carvalho commented on src/components/header/Header.js
> +
Tira esse espaço.

2024-12-01 17:28 UTC, Madson-Carvalho approved these changes

2024-12-01 17:28 UTC, merged